### ISSUE TITLE
How to use plugin without LSP

### ISSUE THREAD

**Issue by eshepelyuk** [kcl-lang/kcl.nvim#7]
Hello, I am not using any LSP in my Neovim setup, so only wanted to use plugin for syntax highlight.
But when I install plugin - i see those kind of errors in every non KCL file.

Some screenshots
1. TOML
![image](https://github.com/kcl-lang/kcl.nvim/assets/1279477/cb9f1ba2-0d1e-4212-b8c3-9849e4257232)

1. YAML
![image](https://github.com/kcl-lang/kcl.nvim/assets/1279477/0618cb85-a930-4a10-a1a2-3b1df92d0bd6)

1. Python
![image](https://github.com/kcl-lang/kcl.nvim/assets/1279477/0c859b8d-602b-4238-a5f6-71667dcae920)

**Comment by He1pa** [comment]
I have fixed this issue now. You can configure the plugin according to the latest README. There are two main updates
1. Set filetype to not start the plugin on non-KCL files
2. If lsp is not installed locally, do not start lsp and only provide highlighting

**Comment by ievgenii-shepeliuk** [comment]
> @eshepelyuk I have fixed this issue now. You can configure the plugin according to the latest README. There are two main updates
> 
> 1. Set filetype to not start the plugin on non-KCL files
> 2. If lsp is not installed locally, do not start lsp and only provide highlighting

Hello, but PR is not yet merged 
https://github.com/kcl-lang/kcl.nvim/pull/8/files

**Comment by He1pa** [comment]
> > @eshepelyuk I have fixed this issue now. You can configure the plugin according to the latest README. There are two main updates
> > 
> > 1. Set filetype to not start the plugin on non-KCL files
> > 2. If lsp is not installed locally, do not start lsp and only provide highlighting
> 
> Hello, but PR is not yet merged https://github.com/kcl-lang/kcl.nvim/pull/8/files

Done

**Comment by eshepelyuk** [comment]
Hello, looks liek working, thank you.
